#!/usr/bin/env python3
"""Generate src/TextEmotePhrases.inc from the client's emote DBCs.

Usage: gen_text_emote_phrases.py <dbfilesclient-dir> [<output.inc>]

<dbfilesclient-dir> must contain EmotesText.dbc and EmotesTextData.dbc
(case-insensitive), extracted from a 3.3.5 client. The output is the phrase
table TextEmoteCatalog.cpp includes: for every emote the client can send,
the third-person lines other players see, reduced to predicate phrases
("blows a raspberry at you") that slot after the actor's name in a prompt.

EmotesText.dbc rows reference EmotesTextData rows by slot, and the slots
encode viewpoint x target x speaker gender. The ones that matter here (the
reacting bot always reads someone else's emote):
    0  "%s waves at %s."     - male speaker, named target
    1  "%s waves at you."    - male speaker, target is the reader
    4  "%s waves."           - male speaker, no target
    8/9/12 - the same three for a female speaker
"""

import os
import struct
import sys

# Emotes whose client text is not "%s <predicate>" (e.g. "Blood oozes from
# %s's wounds.") get hand-written predicates instead; {} is the target name.
OVERRIDES = {
    10: {"none": "bleeds from open wounds."},
    22: {
        "none": "struts around with arms flapping. Cluck, Cluck, Chicken!",
        "you": "struts around you with arms flapping. Cluck, Cluck, Chicken!",
        "named": "struts around {} with arms flapping. Cluck, Cluck, Chicken!",
    },
    36: {"none": "drools, a tendril running down their lip."},
    65: {
        "none": "mourns the loss of the dead in quiet contemplation.",
        "you": "mourns your death in quiet contemplation.",
        "named": "mourns the death of {} in quiet contemplation.",
    },
    131: {"none": "smirks slyly."},
    429: {"none": "shifts their eyes back and forth suspiciously."},
}

# (male slot, female slot) per form, in .inc phrase order.
FORMS = [("none", 4, 12), ("you", 1, 9), ("named", 0, 8)]


def read_dbc(path):
    with open(path, "rb") as f:
        data = f.read()
    magic, records, fields, record_size, string_size = struct.unpack_from("<4sIIII", data, 0)
    assert magic == b"WDBC", path
    assert record_size == fields * 4, path
    table = []
    offset = 20
    for _ in range(records):
        table.append(struct.unpack_from("<%dI" % fields, data, offset))
        offset += record_size
    return table, data[offset:offset + string_size]


def get_string(block, offset):
    if not offset:
        return ""
    return block[offset:block.index(b"\0", offset)].decode("utf-8")


def find_file(directory, name):
    for entry in os.listdir(directory):
        if entry.lower() == name.lower():
            return os.path.join(directory, entry)
    sys.exit(f"{name} not found in {directory}")


def predicate(text, named):
    """'%s waves at you.' -> 'waves at you.'; None when not that shape."""
    text = " ".join(text.split())
    if not text.startswith("%s "):
        return None
    phrase = text[3:].replace("{", "{{").replace("}", "}}")
    if named:
        phrase = phrase.replace("%s", "{}", 1)
    if "%s" in phrase:
        return None
    return phrase


def literal(phrase):
    if phrase is None:
        return "nullptr"
    return '"' + phrase.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    dbc_dir = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "src", "TextEmotePhrases.inc")

    data_table, data_strings = read_dbc(find_file(dbc_dir, "EmotesTextData.dbc"))
    # id + 16 localized columns + flags; enUS is the first localized column.
    texts = {row[0]: get_string(data_strings, row[1]) for row in data_table}

    emote_table, emote_strings = read_dbc(find_file(dbc_dir, "EmotesText.dbc"))

    lines = [
        "// Generated by tools/gen_text_emote_phrases.py from the client's",
        "// EmotesText.dbc / EmotesTextData.dbc. Do not edit by hand.",
        "//",
        "// { id, name, { untargeted, at-you, at-named, and the same three for a",
        "// female actor } } - nullptr means no such line (fall back in that",
        "// order; an all-nullptr emote is animation/sound only).",
    ]
    for row in emote_table:
        emote_id, name = row[0], get_string(emote_strings, row[1])
        slots = row[3:19]
        override = OVERRIDES.get(emote_id, {})

        male = {}
        female = {}
        for form, male_slot, female_slot in FORMS:
            if form in override:
                male[form] = override[form]
                female[form] = None
                continue
            male[form] = female[form] = None
            if slots[male_slot] and (text := texts.get(slots[male_slot])):
                male[form] = predicate(text, form == "named")
            if slots[female_slot] and (text := texts.get(slots[female_slot])):
                female[form] = predicate(text, form == "named")
            if female[form] == male[form]:
                female[form] = None

        phrases = [male[f] for f, _, _ in FORMS] + [female[f] for f, _, _ in FORMS]
        lines.append(f"// {emote_id} {name}")
        lines.append(f'{{ {emote_id}, "{name.lower()}",')
        lines.append("    { " + ",\n      ".join(literal(p) for p in phrases) + " } },")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(emote_table)} emotes to {out_path}")


if __name__ == "__main__":
    main()
